apiVersion: v1
kind: Service
metadata:
  name: web-service-tf09
  labels:
    app: web-tf09
spec:
  type: NodePort
  selector:
    app: web-tf09
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
